groups:
  - name: desktop
    description: Desktop flavor selection
    critical: true
    subgroups:
      - name: kde
        description: KDE Plasma desktop
        default: true
        packages:
          - gayos-kde
