modules-search: [ local ]
sequence:
  - show
  - welcome
  - locale
  - keyboardq
  - localecfg
  - keyboard
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - networkcfg
  - users
  - displaymanager
  - grubcfg
  - bootloader
  - packages
  - shellprocess
  - initramfscfg
  - initcpio
  - hwclock
  - umount
  - summary
  - install
  - finished

branding: gayos
prompt-install: true
dont-chroot: false
oem-setup: false
